# Generated by Django 4.1.5 on 2023-01-18 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_adress', models.CharField(max_length=15)),
                ('video_feed_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Targets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(max_length=150)),
                ('target_photo', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Encounters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enc_time', models.DateTimeField()),
                ('enc_source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.sourcelist')),
                ('enc_target', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.targets')),
            ],
        ),
    ]
