# Generated by Django 4.1.5 on 2023-01-21 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_sourcelist_source'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Encounters',
            new_name='Encounter',
        ),
        migrations.RenameModel(
            old_name='Targets',
            new_name='Target',
        ),
    ]
